### ISSUE TITLE
[BUG] According to the Taiga, your username/email or password are incorrect.

### ISSUE THREAD

**Issue by gerroon** [kaleidos-ventures/taiga-docker#39]
Hi

I just did a Docker pull and I am getting this error in the browser `According to the Taiga, your username/email or password are incorrect.` Bear in mind that my Taiga was working perfectly just before that.

I have already defined a reabbit version based on the previopus botched pull.
```
taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
```

The inspector shows these errrors

![chrome_WbOthcc06c](https://user-images.githubusercontent.com/8519469/130884088-638925dd-782e-414b-82dd-3a54acafcd75.jpg)

So I am not sure what I can do, I am locked out now. This is perplexing, everytime I do a docker pull this is broken, which you can see from my previous bug posts :( 

I am in the middle of a project and all my bugs and tasks are in Taiga, and I cant acces them and my delivery is in couple weeks :(

```
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:01:14:07 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:01:14:09 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
taiga-gateway_1          | 2021/08/26 01:14:09 [error] 31#31: *2319 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.26.0.7:88
88/events", host: "taiga.lan:25080"
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:01:14:10 +0000] "POST /api/v1/auth HTTP/1.1" 502 560 "http://taiga.lan:25080/login?force_login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
taiga-gateway_1          | 2021/08/26 01:14:10 [error] 31#31: *2321 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "POST /api/v1/auth HTTP/1.1", upstream: "http://172.26.0.8:8000/api/v1/auth", host: "taiga.lan:25080", referrer: "http://taiga.lan:25080/login?force_login"
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:01:14:11 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
taiga-gateway_1          | 2021/08/26 01:14:11 [error] 31#31: *2323 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.26.0.7:8888/events", host: "taiga.lan:25080"
taiga-gateway_1          | 2021/08/26 01:14:11 [error] 31#31: *2325 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.26.0.7:88
88/events", host: "taiga.lan:25080"
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:01:14:11 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
taiga-gateway_1          | 2021/08/26 01:14:11 [error] 31#31: *2327 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.26.0.7:88
88/events", host: "taiga.lan:25080"
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:01:14:11 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"
taiga-gateway_1          | 2021/08/26 01:14:12 [error] 31#31: *2329 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.26.0.7:88
88/events", host: "taiga.lan:25080"


```

**Comment by gerroon** [comment]
Maybe this is a db issue at the same time?

```
88/events", host: "taiga.lan:25080"                                                                                                                                                                                                           
taiga-gateway_1          | 2021/08/26 04:18:17 [error] 32#32: *1545 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.18.0.7:88
88/events", host: "taiga.lan:25080"                                                                                                                                                                                                           
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:04:18:17 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"        
taiga-db_1               | 2021-08-26 04:18:18.188 UTC [26] LOG:  redo starts at 0/43E3BB8                                                                                                                                                    
taiga-db_1               | 2021-08-26 04:18:18.188 UTC [26] LOG:  invalid record length at 0/43E3CD8: wanted 24, got 0                                                                                                                        
taiga-db_1               | 2021-08-26 04:18:18.188 UTC [26] LOG:  redo done at 0/43E3CA0                                                                                                                                                      
taiga-gateway_1          | 2021/08/26 04:18:18 [error] 32#32: *1547 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.18.0.7:88
88/events", host: "taiga.lan:25080"                                                                                                                                                                                                           
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:04:18:18 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" "-"        
taiga-gateway_1          | 2021/08/26 04:18:19 [error] 32#32: *1549 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.2.4, server: , request: "GET /events HTTP/1.1", upstream: "http://172.18.0.7:88
88/events", host: "taiga.lan:25080"                                                                                                                                                                                                           
taiga-gateway_1          | 192.168.2.4 - - [26/Aug/2021:04:18:19 +0000] "GET /events HTTP/1.1" 502 560 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"

```

**Comment by gerroon** [comment]
After struggling for many hours with this, I reverted it back to tag 6.2.0 using the Docker release tag and it works again. So it is clear that a change is in 6.3.0 is breaking my deployment not sure if anyone else has the same issue.

**Comment by koshrf** [comment]
I can confirm this bug too, tried 6.3.0 but it says my username/password are wrong and if I try to recover it, it says it doesn't exist.

**Comment by daniel-herrero** [comment]
Hi @gerroon,

Thanks for reporting this. In order to help us understand your context, can you send us a start up `docker-compose logs` report,  your `docker-compose.yml` regarding the affected services, and, if exists, your Ngix or your proxy configuration?

Thank in advance

**Comment by crud42** [comment]
I can confirm the same issue here. It looks like there is no user created at all. Current release does not work with docker-compose up.

@gerroon How did you make it work? When checking out 6.2.0 tag it still pulls in the latest releases frontend, backend , etc.

Best,
Chris

**Comment by gerroon** [comment]
> @gerroon How did you make it work? When checking out 6.2.0 tag it still pulls in the latest releases frontend, backend , etc.
> 
> Best,
> Chris


I just used something like this for all the taiga containers `image: taigaio/taiga-back:6.2.0`

**Comment by gerroon** [comment]
> Hi @gerroon,
> 
> Thanks for reporting this. In order to help us understand your context, can you send us a start up `docker-compose logs` report, your `docker-compose.yml` regarding the affected services, and, if exists, your Ngix or your proxy configuration?
> 
> Thank in advance

I actually do not want to go back to 6.3 since that was quite painful. I am back to 6.2 so I cant provide you any logs but here is my docker compose

```
version: "3.5"

x-environment:
  &default-back-environment
  # Database settings
  POSTGRES_DB: taiga
  POSTGRES_USER: taiga
  POSTGRES_PASSWORD: taiga
  POSTGRES_HOST: taiga-db
  # Taiga settings
  TAIGA_SECRET_KEY: "xxx"
  TAIGA_SITES_DOMAIN: "taiga.lan:10000"
  TAIGA_SITES_SCHEME: "http"
  TAIGA_SUBPATH: ""
  # Email settings. Uncomment following lines and configure your SMTP server
  # EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  # DEFAULT_FROM_EMAIL: "no-reply@example.com"
  # EMAIL_USE_TLS: "False"
  # EMAIL_USE_SSL: "False"
  # EMAIL_HOST: "smtp.host.example.com"
  # EMAIL_PORT: 587
  # EMAIL_HOST_USER: "user"
  # EMAIL_HOST_PASSWORD: "password"
  # Rabbitmq settings
  # Should be the same as in taiga-async-rabbitmq and taiga-events-rabbitmq
  RABBITMQ_USER: taiga
  RABBITMQ_PASS: taiga
  # Telemetry settings
  ENABLE_TELEMETRY: "False"

x-volumes:
  &default-back-volumes
  - /media/taiga2/data:/taiga-back/static
  - /media/taiga2/meddata:/taiga-back/media
  # - ./config.py:/taiga-back/settings/config.py


services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - /media/taiga2/datab:/var/lib/postgresql/data
    networks:
      - taiga
  taiga-back:
    image: taigaio/taiga-back:6.2.0
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq

  taiga-async:
    image: taigaio/taiga-back:6.2.0
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - /media/taiga2/rb:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:6.2.0
    environment:
      TAIGA_URL: "http://taiga.lan:10000"
      TAIGA_WEBSOCKETS_URL: "ws://taiga.lan:10000"
      TAIGA_SUBPATH: "/"
      PUBLIC_REGISTER_ENABLED: "true"
    networks:
      - taiga
    # volumes:
    #   - ./conf.json:/usr/share/nginx/html/conf.json

  taiga-events:
    image: taigaio/taiga-events:6.2.0
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga
      TAIGA_SECRET_KEY: "xxxxx"
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga
      RABBITMQ_DEFAULT_VHOST: taiga
    volumes:
      - /media/taiga2/rb:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:6.2.0
    environment:
      MAX_AGE: 360
      SECRET_KEY: "xxxx"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "10000:80"
      - "8000:8000"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - /media/taiga2/data:/taiga/static
      - /media/taiga2/meddata:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:



```
